version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/install_docker_ubuntu.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 120
      runas: root



